org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.experimental.legacyNativeSupport=false

# Fix untuk flutter_native_splash build issue
org.gradle.configureondemand=false
org.gradle.parallel=true
kotlin.incremental=false

# Disable build cache
android.enableBuildCache=false

# Fix MockableJarTransform error for API 35/36
android.build.generateMockableJar=false

# Bypass AGP version requirements for forced AndroidX libraries
android.experimental.privacysandbox.sdk.enable=false
android.experimental.sdk.verification.external.allow-unsafe=true
