org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# android.enableUnitTestBinaryResources=false (Deprecated)
android.experimental.legacyNativeSupport=false
# Mengaktifkan pembersihan cache build secara otomatis
android.cleanAnalysisCache=true
android.nonTransitiveRClass=false
# Nonaktifkan build cache jika ruang disk sangat terbatas (Opsional)
# android.enableBuildCache=false
